services:
  nginx:
    image: "nginx:stable-alpine"
    ports:
      - "80:80"
    volumes:  
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/simple-sotial-network
    depends_on:
      - php
      - mysql-simple-sotial-network
  php:
    container_name: php-simple-sotial-network
    build: ./dockerfiles/php
    volumes:
      - ./src:/var/www/simple-sotial-network
    user: '1000:1000'
  mysql-simple-sotial-network:
    container_name: mysql-simple-sotial-network
    image: mysql    
    volumes: 
      - ./mysql-simple-sotial-network:/var/lib/mysql
    environment: 
      - MYSQL_ROOT_PASSWORD=root
    env_file:
      - mysql.env
  phpmyadmin:
    container_name: phpmyadmin-sotial-network
    image: phpmyadmin
    ports:
      - 1500:80
    environment: 
      - PMA_HOST=mysql-simple-sotial-network
    depends_on:
      - mysql-simple-sotial-network

volumes:
  mysql-simple-sotial-network: